### ISSUE TITLE
model・DBの作成

### ISSUE THREAD

**Issue by great084** [great084/reform_estimate#5]
以下のモデルDBを作成する。
- Estimate
- EstimateDetail
- UnitPrice
- Category

**Comment by great084** [comment]
migrateでこんなエラー出た。

```
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Column `estimate_id` on table `estimate_details` does not match column `id` on `estimates`, which has type `bigint`. To resolve this issue, change the type of the `estimate_id` column on `estimate_details` to be :bigint. (For example `t.bigint :estimate_id`).
Original message: Mysql2::Error: Referencing column 'estimate_id' and referenced column 'id' in foreign key constraint 'fk_rails_8c8d3301c8' are incompatible.
/Users/hiro/app/reform_estimate/db/migrate/20200930133105_create_estimate_details.rb:15:in `change'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::MismatchedForeignKey: Column `estimate_id` on table `estimate_details` does not match column `id` on `estimates`, which has type `bigint`. To resolve this issue, change the type of the `estimate_id` column on `estimate_details` to be :bigint. (For example `t.bigint :estimate_id`).
Original message: Mysql2::Error: Referencing column 'estimate_id' and referenced column 'id' in foreign key constraint 'fk_rails_8c8d3301c8' are incompatible.
/Users/hiro/app/reform_estimate/db/migrate/20200930133105_create_estimate_details.rb:15:in `change'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Referencing column 'estimate_id' and referenced column 'id' in foreign key constraint 'fk_rails_8c8d3301c8' are incompatible.
/Users/hiro/app/reform_estimate/db/migrate/20200930133105_create_estimate_details.rb:15:in `change'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

他Tableのidを外部キーとして使う場合、型はintegerではなく、bigintになるらしい
